import type { Metadata } from "next";
import "./globals.css";
import React, { Fragment } from "react";
import AppLayout from "@/components/layouts/app-layout";
import ThemeProvider from "@/components/providers/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Fragment>
       <ThemeProvider>
         <AppLayout>{children}</AppLayout>
       </ThemeProvider>
      </Fragment>
    </html>
  );
}
